### ISSUE TITLE
Map: edit initial modal

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-map#34]
Feedback from Owen: for the demo, remove:
- Tour
- Search
- FAQ

**Comment by amygroshek** [comment]
Staged.

**Comment by laurendoone** [comment]
@lougroshek the FAQ button on the modal links to https://hyperobjekt.github.io/faq/ (404 page). Should it link to the Help panel instead?

**Comment by amygroshek** [comment]
Ask the client. I'm sure we can figure that out for whenever they release. The current setup is how it was set up to work for cpal, and this project also has an extensive shell site FAQ page (where the client will be able to edit copy via the CMS so my assumption is, yes, that we will link this to the shell site FAQ page). However, it is irrelevant for 2/26 because the next commit I am about to stage will not show the button for the FAQ in the intro modal. 

When you are reviewing work staged here, remember that this explorer will reside inside of the shell site at the path `/explorer`. So a link from there to `/faq` goes to the shell site faq page.
