### ISSUE TITLE
Map: add general overlay layers

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-map#44]
Feedback from client: Add in some general "overlay" layers, such as Census tract or School District boundaries, similar to how they were done in the CRE

Client needs to determine what data will be presented before we can start design.

**Comment by amygroshek** [comment]
@laurendoone I will want them to add these layers to their existing repository. Alternatively, they could provide them and we could put them permanently into the map application, if they won't change often. 

This brings up another topic, though: we are getting close to the edge of the amount of data we want to download in an unzipped format. It may be time to discuss with the client writing a script to gzip the files and put them into an aws bucket, so they are smaller when we download them. To do that I'd need access to their repo, and because we would be putting an AWS bucket access key into their account we may want it to be their own AWS account. A topic to raise with James when you are able. We discussed AWS with them initially and didn't think we would need it but it would very much improve load times for the map.
